name: PIO build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ["ledmatrix-local"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio --progress-bar off
    - name: Install PlatformIO packages
      run: |
        export GITHASH=$(git describe --always)
        sed -i "3s/dev/$GITHASH/" src/gitHeader.h
        cat src/gitHeader.h
        pio pkg install
    - name: Build
      run: platformio run --environment ${{ matrix.environment }}
    - uses: actions/upload-artifact@v3
      with:
        name: firmware-${{ matrix.environment }}
        path: ./build_output/firmware/